package Telas;

import Controller.LoginController;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Wedson
 * @author Yagor
 */
public class Login extends javax.swing.JFrame {

    private final LoginController controller;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        controller = new LoginController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFechar = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        LoginLabel = new javax.swing.JLabel();
        UsuarioLabel = new javax.swing.JLabel();
        usuarioINPUT = new javax.swing.JTextField();
        SenhaLabel = new javax.swing.JLabel();
        senhaINPUT = new javax.swing.JPasswordField();
        Cadastrar = new javax.swing.JButton();
        loginPainel = new javax.swing.JLabel();
        LoginBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Escolar - Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFechar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 110, 50));

        btnLogin.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnLogin.setText("Acessar");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 110, 50));

        LoginLabel.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        LoginLabel.setForeground(new java.awt.Color(255, 255, 255));
        LoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginLabel.setText("Login");
        LoginLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        LoginLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(LoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, 50));

        UsuarioLabel.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        UsuarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        UsuarioLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsuarioLabel.setText("Usuario");
        UsuarioLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        UsuarioLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(UsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, 30));

        usuarioINPUT.setBackground(new java.awt.Color(153, 153, 153));
        usuarioINPUT.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        usuarioINPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioINPUTActionPerformed(evt);
            }
        });
        getContentPane().add(usuarioINPUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 320, 50));

        SenhaLabel.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        SenhaLabel.setForeground(new java.awt.Color(255, 255, 255));
        SenhaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SenhaLabel.setText("Senha");
        SenhaLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        SenhaLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(SenhaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, 30));

        senhaINPUT.setBackground(new java.awt.Color(153, 153, 153));
        senhaINPUT.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        senhaINPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaINPUTActionPerformed(evt);
            }
        });
        getContentPane().add(senhaINPUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 320, 50));

        Cadastrar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Cadastrar.setText("Cadastrar");
        Cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(Cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 110, 50));

        loginPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/imagens/painel-login.png"))); // NOI18N
        getContentPane().add(loginPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        LoginBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/imagens/loginIMG1.png"))); // NOI18N
        getContentPane().add(LoginBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioINPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioINPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioINPUTActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String nome = usuarioINPUT.getText();
        String senha = senhaINPUT.getText();
        controller.acessar(nome,senha);
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void senhaINPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaINPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaINPUTActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        controller.cadastro();
    }//GEN-LAST:event_CadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    public JPasswordField getSenhaINPUT() {
        return senhaINPUT;
    }

    public void setSenhaINPUT(JPasswordField senhaINPUT) {
        this.senhaINPUT = senhaINPUT;
    }

    public JTextField getUsuarioINPUT() {
        return usuarioINPUT;
    }

    public void setUsuarioINPUT(JTextField usuarioINPUT) {
        this.usuarioINPUT = usuarioINPUT;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JLabel LoginBG;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JLabel SenhaLabel;
    private javax.swing.JLabel UsuarioLabel;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel loginPainel;
    private javax.swing.JPasswordField senhaINPUT;
    private javax.swing.JTextField usuarioINPUT;
    // End of variables declaration//GEN-END:variables

    public void exibeMensagem(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }
}
