package Telas.Cadastro;

import Controller.MenuPrincipalController;
import Model.Aluno;
import Model.Repositorio.AlunoDAO;
import Telas.AlunosView;
import Telas.MenuPrincipal;
import javax.swing.JOptionPane;

/**
 *
 * @author Wedson
 * @author Yagor
 */
public class AlunoCadastro extends javax.swing.JPanel {
    private final MenuPrincipalController controller;
    private final MenuPrincipal menu;
    private Aluno aluno;
    private boolean editar;
    

    /**
     * Creates new form AlunoCadastro
     */
    public AlunoCadastro(MenuPrincipal menu) {
        initComponents();
        this.menu = menu;
        controller = menu.getController();
        this.editar = false;
    }
    
    public AlunoCadastro(MenuPrincipal menu, Aluno aluno){
        initComponents();
        this.menu = menu;
        controller = menu.getController();
        this.editar = true;
        alunoIdInput.setText(String.valueOf(aluno.getId()));
        alunoIdInput.setEditable(false);
        alunoNomeInput.setText(aluno.getNome());
        alunoEnderecoInput.setText(aluno.getEndereco());
        alunoTelefoneInput.setText(aluno.getTelefone());
        alunoEmailInput.setText(aluno.getEmail());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Main = new javax.swing.JPanel();
        alunoNomeInput = new javax.swing.JTextField();
        alunoNome = new javax.swing.JLabel();
        alunoEndereco = new javax.swing.JLabel();
        alunoEnderecoInput = new javax.swing.JTextField();
        alunoTelefone = new javax.swing.JLabel();
        alunoEmail = new javax.swing.JLabel();
        alunoTelefoneInput = new javax.swing.JTextField();
        alunoEmailInput = new javax.swing.JTextField();
        alunoID = new javax.swing.JLabel();
        alunoIdInput = new javax.swing.JTextField();
        Footer = new javax.swing.JPanel();
        voltar = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        limpar = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        Header.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastrar Aluno");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(193, 193, 193))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        add(Header);

        alunoNomeInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        alunoNomeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoNomeInputActionPerformed(evt);
            }
        });

        alunoNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        alunoNome.setText("Nome:");

        alunoEndereco.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        alunoEndereco.setText("Endereço:");

        alunoEnderecoInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        alunoEnderecoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoEnderecoInputActionPerformed(evt);
            }
        });

        alunoTelefone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        alunoTelefone.setText("Telefone:");

        alunoEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        alunoEmail.setText("Email:");

        alunoTelefoneInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        alunoTelefoneInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoTelefoneInputActionPerformed(evt);
            }
        });

        alunoEmailInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        alunoEmailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoEmailInputActionPerformed(evt);
            }
        });

        alunoID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        alunoID.setText("ID:");

        alunoIdInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        alunoIdInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoIdInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainLayout.createSequentialGroup()
                        .addComponent(alunoEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(alunoEmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, MainLayout.createSequentialGroup()
                        .addComponent(alunoEndereco)
                        .addGap(22, 22, 22)
                        .addComponent(alunoEnderecoInput))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, MainLayout.createSequentialGroup()
                        .addComponent(alunoTelefone)
                        .addGap(28, 28, 28)
                        .addComponent(alunoTelefoneInput))
                    .addGroup(MainLayout.createSequentialGroup()
                        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alunoNome)
                            .addComponent(alunoID))
                        .addGap(50, 50, 50)
                        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alunoNomeInput)
                            .addComponent(alunoIdInput))))
                .addGap(120, 120, 120))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(alunoID)
                    .addComponent(alunoIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(MainLayout.createSequentialGroup()
                        .addComponent(alunoNome)
                        .addGap(25, 25, 25)
                        .addComponent(alunoEndereco)
                        .addGap(25, 25, 25)
                        .addComponent(alunoTelefone))
                    .addGroup(MainLayout.createSequentialGroup()
                        .addComponent(alunoNomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(alunoEnderecoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(alunoTelefoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alunoEmail)
                    .addComponent(alunoEmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        add(Main);

        voltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        cadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        limpar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrar)
                .addGap(122, 122, 122))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltar)
                    .addComponent(cadastrar)
                    .addComponent(limpar))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        add(Footer);
    }// </editor-fold>//GEN-END:initComponents

    private void alunoNomeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoNomeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alunoNomeInputActionPerformed

    private void alunoEnderecoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoEnderecoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alunoEnderecoInputActionPerformed

    private void alunoTelefoneInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoTelefoneInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alunoTelefoneInputActionPerformed

    private void alunoEmailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoEmailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alunoEmailInputActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        if(!editar){
            alunoIdInput.setText("");
        }
        alunoNomeInput.setText("");
        alunoEnderecoInput.setText("");
        alunoTelefoneInput.setText("");
        alunoEmailInput.setText("");
    }//GEN-LAST:event_limparActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        AlunosView alunos = new AlunosView(menu);
        controller.navegar(alunos);
    }//GEN-LAST:event_voltarActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        String msg = "Ops, algo de errado não está certo..";
        try{
            int id = Integer.parseInt(alunoIdInput.getText());
            String nome = alunoNomeInput.getText();
            String endereco = alunoEnderecoInput.getText();
            String telefone = alunoEnderecoInput.getText();
            String email = alunoEmailInput.getText();
            aluno = new Aluno(nome, endereco, telefone, email, id);
            AlunoDAO alunos = new AlunoDAO();
        
            if(editar && alunos.atualizar(aluno)){
                msg = "Cadastro Atualizado!";
            
            } else if(alunos.adicionar(aluno)){
                msg = "Aluno Cadastrado!";
                //limpar formulario
                alunoIdInput.setText("");
                alunoNomeInput.setText("");
                alunoEnderecoInput.setText("");
                alunoTelefoneInput.setText("");
                alunoEmailInput.setText("");
            }
        } catch(Exception e){
            e.printStackTrace();
        } finally{
            JOptionPane.showMessageDialog(null,msg);
        }
        
        
    }//GEN-LAST:event_cadastrarActionPerformed

    private void alunoIdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoIdInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alunoIdInputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Main;
    private javax.swing.JLabel alunoEmail;
    private javax.swing.JTextField alunoEmailInput;
    private javax.swing.JLabel alunoEndereco;
    private javax.swing.JTextField alunoEnderecoInput;
    private javax.swing.JLabel alunoID;
    private javax.swing.JTextField alunoIdInput;
    private javax.swing.JLabel alunoNome;
    private javax.swing.JTextField alunoNomeInput;
    private javax.swing.JLabel alunoTelefone;
    private javax.swing.JTextField alunoTelefoneInput;
    private javax.swing.JButton cadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton limpar;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
