package Telas.Cadastro;

import Controller.MenuPrincipalController;
import Model.Curso;
import Model.Repositorio.CursoDAO;
import Telas.CursosView;
import Telas.MenuPrincipal;
import javax.swing.JOptionPane;

/**
 *
 * @author Wedson
 * @author Yagor
 */
public class CursoCadastro extends javax.swing.JPanel {
    private final MenuPrincipalController controller;
    private final MenuPrincipal menu;
    private boolean editar;
    private Curso curso;
    

    /**
     * Creates new form CursoCadastro
     */
    public CursoCadastro(MenuPrincipal menu) {
        initComponents();
        this.menu = menu;
        controller = menu.getController();
        editar = false;
    }
    
    public CursoCadastro(MenuPrincipal menu, Curso curso){
        initComponents();
        this.menu = menu;
        controller = menu.getController();
        editar = true;

        cursoIDInput.setText(String.valueOf(curso.getId()));
        cursoIDInput.setEditable(false);
        cursoNomeInput.setText(curso.getNome());
        cursoDescricaoInput.setText(curso.getDescricao());
        cursoTurnoBox.setSelectedItem(curso.getTurno());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        cadastrarCurso = new javax.swing.JLabel();
        Main = new javax.swing.JPanel();
        cursoNome = new javax.swing.JLabel();
        cursoDescricao = new javax.swing.JLabel();
        cursoTurno = new javax.swing.JLabel();
        cursoNomeInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cursoDescricaoInput = new javax.swing.JTextArea();
        cursoTurnoBox = new javax.swing.JComboBox<>();
        cursoID = new javax.swing.JLabel();
        cursoIDInput = new javax.swing.JTextField();
        Footer = new javax.swing.JPanel();
        voltar = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        limpar = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        Header.setOpaque(false);

        cadastrarCurso.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        cadastrarCurso.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarCurso.setText("Cadastrar Curso");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(cadastrarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(193, 193, 193))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cadastrarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        add(Header);

        cursoNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cursoNome.setText("Nome:");

        cursoDescricao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cursoDescricao.setText("Descrição:");

        cursoTurno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cursoTurno.setText("Turno:");

        cursoNomeInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        cursoDescricaoInput.setColumns(20);
        cursoDescricaoInput.setRows(5);
        jScrollPane1.setViewportView(cursoDescricaoInput);

        cursoTurnoBox.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        cursoTurnoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutino", "Vespertino", "Noturno", "Integral" }));

        cursoID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cursoID.setText("ID:");

        cursoIDInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainLayout.createSequentialGroup()
                        .addComponent(cursoNome)
                        .addGap(50, 50, 50)
                        .addComponent(cursoNomeInput))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainLayout.createSequentialGroup()
                        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainLayout.createSequentialGroup()
                                .addComponent(cursoID)
                                .addGap(76, 76, 76)
                                .addComponent(cursoIDInput))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainLayout.createSequentialGroup()
                                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cursoDescricao)
                                    .addComponent(cursoTurno))
                                .addGap(20, 20, 20)
                                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cursoTurnoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(113, 113, 113))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursoID)
                    .addComponent(cursoIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursoNome)
                    .addComponent(cursoNomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursoTurno)
                    .addComponent(cursoTurnoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cursoDescricao)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(Main);

        voltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        cadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        limpar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrar)
                .addGap(112, 112, 112))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltar)
                    .addComponent(cadastrar)
                    .addComponent(limpar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add(Footer);
    }// </editor-fold>//GEN-END:initComponents

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        if(!editar){
            cursoIDInput.setText("");
        }
        cursoNomeInput.setText("");
        cursoDescricaoInput.setText("");
    }//GEN-LAST:event_limparActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        CursosView cursos = new CursosView(menu);
        controller.navegar(cursos);
    }//GEN-LAST:event_voltarActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        String msg = "Ops, algo de errado não está certo ...";
        try{
            int id = Integer.parseInt(cursoIDInput.getText());
            String nome = cursoNomeInput.getText();
            String descricao = cursoDescricaoInput.getText();
            String turno = cursoTurnoBox.getSelectedItem().toString();
            curso = new Curso(id, nome, descricao, turno);
            CursoDAO cursos = new CursoDAO();
            
            if(editar && cursos.atualizar(curso)){
                msg = "Curso Atualizado!";
            } else if(cursos.adicionar(curso)){
                msg = "Curso Cadastrado!";
                //limpar formulario
                cursoIDInput.setText("");
                cursoNomeInput.setText("");
                cursoDescricaoInput.setText("");
            }
            
        } catch(Exception e) {
            e.printStackTrace();
        } finally {
            JOptionPane.showMessageDialog(null, msg);
        }
    }//GEN-LAST:event_cadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Main;
    private javax.swing.JButton cadastrar;
    private javax.swing.JLabel cadastrarCurso;
    private javax.swing.JLabel cursoDescricao;
    private javax.swing.JTextArea cursoDescricaoInput;
    private javax.swing.JLabel cursoID;
    private javax.swing.JTextField cursoIDInput;
    private javax.swing.JLabel cursoNome;
    private javax.swing.JTextField cursoNomeInput;
    private javax.swing.JLabel cursoTurno;
    private javax.swing.JComboBox<String> cursoTurnoBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpar;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
