package Telas.Cadastro;

import Controller.MenuPrincipalController;
import Controller.TurmasController;
import Model.Curso;
import Model.Disciplina;
import Model.Professor;
import Model.Repositorio.TurmaDAO;
import Model.Turma;
import Telas.TurmasView;
import Telas.MenuPrincipal;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Wedson
 * @author Yagor
 */
public class TurmaCadastro extends javax.swing.JPanel {
    private final MenuPrincipalController controller;
    private final MenuPrincipal menu;
    private final TurmasController controllerT;
    private boolean editar;
    private Turma turma;
    

    /**
     * Creates new form TurmaCadastro
     */
    public TurmaCadastro(MenuPrincipal menu) {
        initComponents();
        this.menu = menu;
        controller = menu.getController();
        controllerT = new TurmasController(this);
        editar = false;
        iniciar();
    }
    
    public TurmaCadastro(MenuPrincipal menu, Turma turma){
        initComponents();
        this.menu = menu;
        controller = menu.getController();
        controllerT = new TurmasController(this);
        editar = true;
        iniciar();
        
        turmaIDInput.setText(String.valueOf(turma.getId()));
        turmaIDInput.setEditable(false);
        TurmaBoxCurso.getModel().setSelectedItem(turma.getCurso());
        TurmaBoxDisciplina.getModel().setSelectedItem(turma.getDisciplina());
        TurmaBoxProfessor.getModel().setSelectedItem(turma.getProfessor());
        TurmaBoxTurno.getModel().setSelectedItem(turma.getTurno());
        turmaHorarioInput.setText(String.valueOf(turma.getHorario()));
        turmaPeriodoInput.setText(turma.getPeriodo());
    }
    
    
    public void iniciar(){
        this.controllerT.listarCurso();
        this.controllerT.listarDisciplina();
        this.controllerT.listarProfessor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        turmaCadastro = new javax.swing.JLabel();
        Main = new javax.swing.JPanel();
        TurmaCodigo = new javax.swing.JLabel();
        turmaIDInput = new javax.swing.JTextField();
        TurmaHorario = new javax.swing.JLabel();
        turmaPeriodoInput = new javax.swing.JTextField();
        TurmaCurso = new javax.swing.JLabel();
        TurmaBoxCurso = new javax.swing.JComboBox<>();
        TurmaProfessor = new javax.swing.JLabel();
        TurmaBoxProfessor = new javax.swing.JComboBox<>();
        TurmaDisciplina = new javax.swing.JLabel();
        TurmaBoxDisciplina = new javax.swing.JComboBox<>();
        TurmaTurno = new javax.swing.JLabel();
        TurmaBoxTurno = new javax.swing.JComboBox<>();
        TurmaPeriodo = new javax.swing.JLabel();
        turmaHorarioInput = new javax.swing.JTextField();
        Footer = new javax.swing.JPanel();
        voltar = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        limpar = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        Header.setForeground(new java.awt.Color(255, 255, 255));
        Header.setOpaque(false);

        turmaCadastro.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        turmaCadastro.setForeground(new java.awt.Color(255, 255, 255));
        turmaCadastro.setText("Cadastrar Turma");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(turmaCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(193, 193, 193))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(turmaCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        add(Header);

        TurmaCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TurmaCodigo.setText("ID:");

        turmaIDInput.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        turmaIDInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turmaIDInputActionPerformed(evt);
            }
        });

        TurmaHorario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TurmaHorario.setText("Horario:");

        turmaPeriodoInput.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        turmaPeriodoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turmaPeriodoInputActionPerformed(evt);
            }
        });

        TurmaCurso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TurmaCurso.setText("Curso:");

        TurmaBoxCurso.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        TurmaBoxCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TurmaBoxCursoActionPerformed(evt);
            }
        });

        TurmaProfessor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TurmaProfessor.setText("Professor:");

        TurmaBoxProfessor.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N

        TurmaDisciplina.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TurmaDisciplina.setText("Disciplina");

        TurmaBoxDisciplina.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N

        TurmaTurno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TurmaTurno.setText("Turno:");

        TurmaBoxTurno.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        TurmaBoxTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutino", "Vespertino", "Integral", "Noturno" }));

        TurmaPeriodo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TurmaPeriodo.setText("Periodo:");

        turmaHorarioInput.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        turmaHorarioInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turmaHorarioInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainLayout.createSequentialGroup()
                        .addComponent(TurmaProfessor)
                        .addGap(18, 18, 18)
                        .addComponent(TurmaBoxProfessor, 0, 148, Short.MAX_VALUE)
                        .addGap(326, 326, 326))
                    .addGroup(MainLayout.createSequentialGroup()
                        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TurmaDisciplina)
                            .addComponent(TurmaCurso)
                            .addComponent(TurmaCodigo))
                        .addGap(23, 23, 23)
                        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainLayout.createSequentialGroup()
                                .addComponent(turmaIDInput)
                                .addGap(18, 18, 18)
                                .addComponent(TurmaHorario)
                                .addGap(30, 30, 30)
                                .addComponent(turmaHorarioInput, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                                .addComponent(TurmaBoxCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(TurmaPeriodo)
                                .addGap(27, 27, 27)
                                .addComponent(turmaPeriodoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                                .addComponent(TurmaBoxDisciplina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(TurmaTurno)
                                .addGap(41, 41, 41)
                                .addComponent(TurmaBoxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69))))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TurmaCodigo)
                    .addComponent(turmaIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TurmaHorario)
                    .addComponent(turmaHorarioInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TurmaPeriodo)
                    .addComponent(turmaPeriodoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TurmaBoxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TurmaCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TurmaBoxDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TurmaDisciplina)
                    .addComponent(TurmaBoxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TurmaTurno))
                .addGap(41, 41, 41)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TurmaBoxProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TurmaProfessor))
                .addGap(45, 45, 45))
        );

        add(Main);

        voltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        cadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        limpar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addComponent(limpar)
                .addGap(18, 18, 18)
                .addComponent(cadastrar)
                .addGap(29, 29, 29))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrar)
                    .addComponent(limpar)
                    .addComponent(voltar))
                .addGap(30, 30, 30))
        );

        add(Footer);
    }// </editor-fold>//GEN-END:initComponents

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        if(!editar){
            turmaIDInput.setText("");
        }
        turmaHorarioInput.setText("");
        turmaPeriodoInput.setText("");
    }//GEN-LAST:event_limparActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        TurmasView turmas = new TurmasView(menu);
        controller.navegar(turmas);
    }//GEN-LAST:event_voltarActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        String msg = "Ops, algo de errado não esta certo..";
        try{
            int id = Integer.parseInt(turmaIDInput.getText());
            Curso curso = (Curso) TurmaBoxCurso.getSelectedItem();
            Professor prof = (Professor) TurmaBoxProfessor.getSelectedItem();
            Disciplina disc = (Disciplina) TurmaBoxDisciplina.getSelectedItem();
            int horario = Integer.parseInt(turmaHorarioInput.getText());
            String turno = (String) TurmaBoxTurno.getSelectedItem();
            String periodo = turmaPeriodoInput.getText();
            turma = new Turma(id, curso, prof, disc, horario, turno, periodo);
            TurmaDAO turmas = new TurmaDAO();
            
            if(editar && turmas.atualizar(turma)){
                msg = "Turma Atualizada!";
            } else if(turmas.adicionar(turma)){
                msg = "Turma Adicionada!";
                //limpar formulario
                turmaIDInput.setText("");
                turmaHorarioInput.setText("");
                turmaPeriodoInput.setText("");
            }
        } catch(Exception e){
            e.printStackTrace();
            
        } finally {
            JOptionPane.showMessageDialog(null, msg);
        }
        
    }//GEN-LAST:event_cadastrarActionPerformed

    private void turmaIDInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turmaIDInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_turmaIDInputActionPerformed

    private void turmaPeriodoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turmaPeriodoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_turmaPeriodoInputActionPerformed

    private void turmaHorarioInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turmaHorarioInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_turmaHorarioInputActionPerformed

    private void TurmaBoxCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TurmaBoxCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TurmaBoxCursoActionPerformed

    public JComboBox<String> getTurmaBoxCurso() {
        return TurmaBoxCurso;
    }

    public void setTurmaBoxCurso(JComboBox<String> TurmaBoxCurso) {
        this.TurmaBoxCurso = TurmaBoxCurso;
    }

    public JComboBox<String> getTurmaBoxDisciplina() {
        return TurmaBoxDisciplina;
    }

    public void setTurmaBoxDisciplina(JComboBox<String> TurmaBoxDisciplina) {
        this.TurmaBoxDisciplina = TurmaBoxDisciplina;
    }

    public JComboBox<String> getTurmaBoxProfessor() {
        return TurmaBoxProfessor;
    }

    public void setTurmaBoxProfessor(JComboBox<String> TurmaBoxProfessor) {
        this.TurmaBoxProfessor = TurmaBoxProfessor;
    }

    public JComboBox<String> getTurmaBoxTurno() {
        return TurmaBoxTurno;
    }

    public void setTurmaBoxTurno(JComboBox<String> TurmaBoxTurno) {
        this.TurmaBoxTurno = TurmaBoxTurno;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Main;
    private javax.swing.JComboBox<String> TurmaBoxCurso;
    private javax.swing.JComboBox<String> TurmaBoxDisciplina;
    private javax.swing.JComboBox<String> TurmaBoxProfessor;
    private javax.swing.JComboBox<String> TurmaBoxTurno;
    private javax.swing.JLabel TurmaCodigo;
    private javax.swing.JLabel TurmaCurso;
    private javax.swing.JLabel TurmaDisciplina;
    private javax.swing.JLabel TurmaHorario;
    private javax.swing.JLabel TurmaPeriodo;
    private javax.swing.JLabel TurmaProfessor;
    private javax.swing.JLabel TurmaTurno;
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton limpar;
    private javax.swing.JLabel turmaCadastro;
    private javax.swing.JTextField turmaHorarioInput;
    private javax.swing.JTextField turmaIDInput;
    private javax.swing.JTextField turmaPeriodoInput;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
